// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVeLG95FaqbBRtPGOo9o_KvSrqDxK99ss',
    appId: '1:424002589577:web:3f5d56d0d1d1557641c758',
    messagingSenderId: '424002589577',
    projectId: 'simo-app-scada',
    authDomain: 'simo-app-scada.firebaseapp.com',
    storageBucket: 'simo-app-scada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAslTSFIdyvkyp1-wo2ll4_gy9Zf1SfUU8',
    appId: '1:424002589577:android:c575b5382c4cea1441c758',
    messagingSenderId: '424002589577',
    projectId: 'simo-app-scada',
    storageBucket: 'simo-app-scada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQF0i-A-VtvJyRyufcbV2FF7bYZfePtk0',
    appId: '1:424002589577:ios:2630f234047ae71441c758',
    messagingSenderId: '424002589577',
    projectId: 'simo-app-scada',
    storageBucket: 'simo-app-scada.firebasestorage.app',
    iosBundleId: 'com.example.simoAppScada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQF0i-A-VtvJyRyufcbV2FF7bYZfePtk0',
    appId: '1:424002589577:ios:2630f234047ae71441c758',
    messagingSenderId: '424002589577',
    projectId: 'simo-app-scada',
    storageBucket: 'simo-app-scada.firebasestorage.app',
    iosBundleId: 'com.example.simoAppScada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVeLG95FaqbBRtPGOo9o_KvSrqDxK99ss',
    appId: '1:424002589577:web:80e55ad8c7cd23d841c758',
    messagingSenderId: '424002589577',
    projectId: 'simo-app-scada',
    authDomain: 'simo-app-scada.firebaseapp.com',
    storageBucket: 'simo-app-scada.firebasestorage.app',
  );
}
